### ISSUE TITLE
Error in the end of the installation

### ISSUE THREAD

**Issue by madebypixel02** [kishorv06/ChromePad#4] opened 2019-11-21 16:55 UTC
After some time installing stuff, I get the following error:
```
eudev: Gentoo standalone udev
https://wiki.gentoo.org/wiki/Project:Eudev
version 3.2.7
The following packages also need to be installed: 
libxslt libxml2_python libgcrypt libgpgerror docbook_xsl docbook_xml docbook sgml_common gperf util_linux libcap_ng python3 bz2 xzutils sqlite libedit krb5 libtirpc vdev fuse libpstat fskit lvm2 
Do you agree? [Y/n] I don't understand `p`. :(
No changes made.
```

**Comment by kishorviswanathan** [comment] 2020-02-15 15:29
The issue is fixed now. Crew now prompts for a user input. So I have piped "yes" to crew install command.

**Closed as completed** 2020-02-15 15:29 UTC

**Comment by madebypixel02** [comment] 2020-02-17 20:19
Yep, issue fixed, thanks!
